#!/usr/bin/env python
year = "2023"
day = ""
test = False

import os,sys, importlib

sys.dont_write_bytecode = True
dir_path = os.path.dirname(os.path.realpath(__file__))
dir_path = dir_path.replace("/bin", "")

def validate_day(day):
    if day == "":
        print("Usage: solve [-t] [day]")
        exit()
    elif not day.isnumeric() or int(day) < 1 or int(day) > 25:
        print("Invalid day: " + day)
        exit()
    return int(day)

 
for arg in sys.argv[1:]:
    match arg:
        case "-t":
            test = True
        case default:
            day = arg

day = validate_day(day)
solution = importlib.import_module(f"{year}.{day}.solution")
tests = importlib.import_module(f"{year}.{day}.tests")
input_string = open(f"{dir_path}/{year}/{day}/input.txt").read()

def run_part(solution, tests):
    passed = 0
    for (input_string_test, answer) in tests():
        a = solution(input_string_test)
        print(f"actual: {a}", end="")
        if a == answer or answer == None:
            if a == answer:
                print(f", expected: { answer } \u2705")
            else:
                print(" \u2753")
            passed += 1
        else:
            print(f", expected: { answer } \u274c")
    print(f"passed {passed}/{len(tests())} tests")
    if not test:
        print(f"answer: { solution(input_string) }")

run_part(solution.part_one, tests.part_one)
print()
run_part(solution.part_two, tests.part_two)